### ISSUE TITLE
Does Donkey support HTTP/2 for gRPC?

### ISSUE THREAD

**Issue by theronic** [AppsFlyer/donkey#14]
Vert.x supports HTTP2, but there is no mention of it in Donkey docs or repo. Is HTTP/2 supported? Specifically I need it for gRPC.

**Comment by yaronel** [comment]
Unfortunately not yet.
This is something we want to add, though I don't have a date estimate.

**Comment by yaronel** [comment]
Closing issue.
Once support for HTTP/2 is added I'll mention this issue.
