### ISSUE TITLE
wrap-resource causes 500 on match

### ISSUE THREAD

**Issue by SevereOverfl0w** [AppsFlyer/donkey#17]
**Describe the bug**
When using `wrap-resource`, 500 exceptions are raised for resources.

**To Reproduce**

```
;; src/foo.clj
(defonce server
  (doto
    (create-server
      (create-donkey)
      {:port 8080
       :routes [{:handler-mode :blocking
                 :methods [:get]
                 :handler (fn [_]
                            {:status 200
                             :body "did not match a resource"})
                 :middleware [#(ring.middleware.resource/wrap-resource % "static")]
                 }]
       :date-header true})
    start-sync))
```

```
;; src/static/foo.txt
matched!
```

When hitting http://localhost:8080/foo.txt there will be a 500 error, that never terminates in the browser. `curl -v` is the best way to see.

**Expected behavior**
foo.txt is served

**Desktop (please complete the following information):**
 skipping, because not relevant?

**Smartphone (please complete the following information):**
 skipping, because not relevant?

**Comment by yaronel** [comment]
I ran the example with a debugger and the ring middleware is not able to find the resource.
This is not an issue with Donkey. 
According to the docs the resource needs to be on the classpath.
Also, it is not a good idea to serve static resources from the code `src` folder.

**Comment by SevereOverfl0w** [comment]
I just tried this, and I'm seeing different behavior to you.  Using styles.cs because happens to be in my static folder at this time:

```
~
❯ curl -v localhost:8080/styles.css
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /styles.css HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.75.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Length: 1749
< Last-Modified: Sat, 13 Feb 2021 21:25:46 GMT
< Date: Sat, 13 Feb 2021 21:49:30 GMT
< 
^C

~
❯ curl -v localhost:8080/literallyanythingelse
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /literallyanythingelse HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.75.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 24
< Date: Sat, 13 Feb 2021 21:49:39 GMT
< 
* Connection #0 to host localhost left intact
did not match a resource%                                                             
```

What did you see when trying to run this?

**Comment by yaronel** [comment]
I ran the server in the repl, and then accessed the url from the browser. 
In both cases I got a 200 response with the default text in the body. 

If you paste the output from the server logs then I might be able to get an idea what is the cause of the error.

**Comment by SevereOverfl0w** [comment]
Ah, I added slf4j and now I get stacktraces!

```
[vert.x-worker-thread-1] ERROR com.appsflyer.donkey.server.handler.InternalServerErrorHandler - Internal Server Error:
com.appsflyer.donkey.client.exception.UnsupportedDataTypeException: Cannot create a byte[] from java.io.File. Only String and InputStream are supported.
	at com.appsflyer.donkey.util.TypeConverter.toBytes(TypeConverter.java:121)
	at com.appsflyer.donkey.util.TypeConverter.toBuffer(TypeConverter.java:127)
	at com.appsflyer.donkey.server.ring.handler.RingResponseAdapter.sendResponse(RingResponseAdapter.java:66)
	at com.appsflyer.donkey.server.ring.handler.RingResponseAdapter.handle(RingResponseAdapter.java:48)
	at com.appsflyer.donkey.server.ring.handler.RingResponseAdapter.handle(RingResponseAdapter.java:28)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1107)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:114)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at com.appsflyer.donkey.route.BlockingRouteHandler.handle(route.clj:113)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://github.com/ring-clojure/ring/blob/2ba9779a817b56fb38118cc8abcd04d68c620ff1/ring-core/src/ring/util/response.clj#L266-L270 caused by the fact that ring.middleware.resource will hit this path if you're hosting from the filesystem.

**Comment by yaronel** [comment]
OK, that's a valid issue.
There are two scenarios that should be handled here. 
1. Progrematically sending a response with a file. For example, an application that generates a PDF invoice on demand. 
2. Serving static content

The first case is simple to handle and will be transparent to the user. It basically adds support for the body of a response to be an instance of `java.io.File`.
The second case requires an API for the user to declare that some path(s) should be served statically, bypassing the creating of a Ring request/response.

I'll be happy to hear suggestions.

**Comment by barkanido** [comment]
How would you do this directly in vertx?

**Comment by yaronel** [comment]
> How would you do this directly in vertx?

@barkanido - The Vert.x `HttpServerResponse` interface has a `sendFile` method.
Just created a PR that handles it - #18

**Comment by yaronel** [comment]
For static resources we could add an option when creating a server - `:resources [map[, map]*]` which will be the same as the `:routes` vector, except the map will include only a subset of the fields the route map accepts:
- :path
- :match-type
- :methods
- :consumes
- :produces

Any thoughts?

**Comment by yaronel** [comment]
@SevereOverfl0w - this issue is handled in PR #20 if you want to test it out.
Though I still need to add documentation.
