### ISSUE TITLE
Support extra arity on create-server that meets the Ring spec for adapters

### ISSUE THREAD

**Issue by didibus** [AppsFlyer/donkey#9]
**Is your feature request related to a problem? Please describe.**

The Ring spec for adapters says:

> Adapters are implemented as functions of two arguments: a handler and an options map. The options map provides any needed configuration to the adapter, such as the port on which to run.

The Donkey `create-server` is thus not a valid Ring Adapter, because its a function of a single argument: an options map. Its unfortunate, since Donkey is compliant with Ring Handlers and Middleware, it would be nice for it to be compliant with Ring Adapters as well.

**Describe the solution you'd like**

If a new arity for `create-server` was provided which takes two arguments: a handler and an options map, it would become a valid Ring Adapter.

**Describe alternatives you've considered**

None yet.

**Additional context**

From what I understand, since Donkey handles routing by default, and the Donkey routing isn't implemented as a Ring Handler, like it is for reitit and Compojure, it could explain why `create-server` was designed this way, as you'd most likely want to pass multiple handlers to `create-server`, one per route, so putting it in the options map makes sense. That said, I think it be nice to provide a compatibility layer similarly here, where if called with the arity that is Ring Adapter compatible, it defaults to not having any routing. And ideally, similar to reitit, the Donkey routing could also provide a Ring compliant Handler interface, so one could use it fully compliant with Ring:

```
(def app
  (donkey/routes-handler
   {:routes [{:path "/greet"
              :methods [:get]
              :handler (fn [req res _err]
                         (res {:body (str "Hello, "
                                          (get-in req [:query-params "fname"])
                                          " "
                                          (get-in req [:query-params "lname"]))}))
              :middleware [(parse-query-params)]}]}))

(->
 (create-donkey)
 (create-server app {:port 8080
                     :handler-mode :blocking})
 start)
```

**Comment by yaronel** [comment]
I understand it doesn't follow the Ring Adapter Spec.
Can you describe a use-case in which you will use Donkey with an adapter?

You can achieve what you want by creating a server with a single route that delegates to the adapter.
See: https://github.com/AppsFlyer/donkey#reitit

Let me know if I misunderstood.

**Comment by didibus** [comment]
Its a minor issue, the benefit of following the adapter spec is slightly easier to switch back and forth between different servers from a Ring app. Donkey is compatible with Ring handlers and middlewares, and that's the crux of a Ring app, so the adapter part is very minor, but since Donkey is so close to being fully compliant with Ring, I thought I'd open an issue.

**Comment by yaronel** [comment]
I see. 
OK, that's good that you pointed it out.
However, looking at the example you posted, it will make for an awkward API when added to the existing one. 
Given that it's entirely possible to use an adapter today, I opt not to implement it.
